### ISSUE TITLE
Unable to run implicit_amber_tutorial.py

### ISSUE THREAD

**Issue by yipy0005** [gpantel/MD_methods-and-analysis#1]
Hi, I was trying to follow your tutorial and run the `implicit_amber_tutorial.py` file. Minimization went okay but when it comes to running the actual MD simulation, I encountered `openmm.OpenMMException: Particle coordinate is nan`.

Is there some variables that I probably have to set to circumvent this problem?

Thanks. :)

**Comment by gpantel** [comment]
Hi Yip Yew, thanks for the question.

I made this example quite some time ago, allow me to try it again later this evening when I can get to a computer.

Can you ensure that your OpenMM passes the sanity check "python -m simtk.testInstallation"?

**Comment by gpantel** [comment]
Hi Yip Yew,

I apologize, the PDB file in that directory was the issue. I've replaced it with a PDB file containing the same initial, extended conformation of trpcage which will nonetheless work properly. Please try.

**Comment by yipy0005** [comment]
Hi George, it works perfectly now! Thanks for fixing it! Your tutorials are really useful for me and my peers who are new to OpenMM. :D
