### ISSUE TITLE
Mixing entropy

### ISSUE THREAD

**Issue by bondrewd** [gpantel/MD_methods-and-analysis#2]
Hi! Thank you very much for sharing your analysis programs on GitHub!

I was trying to calculate the mixing entropy following your implementation and found the following line:

https://github.com/gpantel/MD_methods-and-analysis/blob/874f022b4be4e3fff241cee28026f396c69c67ab/membrane_analysis/ternary_lipid_voronoi_edges.py#L296

I was wondering if this is a bug since the mixing entropy is defined as:

```
S = -p1*log(p1) - p2*log(p2)
```

Thank you!

**Comment by gpantel** [comment]
Hi Diago,

Thanks for your email.

No it's not a bug. Conventionally you'd use the natural log for mixing
entropy but as discussed in this post (
https://gpantel.github.io/analysis-method/mixent/) I'm using log base 2
such that the maximum in the mixing entropy is 1.

Best wishes,
George

**Comment by bondrewd** [comment]
Thank you very much for your reply! I'm sorry that I did not explain myself. I understand that the base of the `log` depends on the number of components.

My question was regarding the sign in the expression. In the expression, I found you are adding the second term instead of subtracting it `+( X_DL * np.log2(X_DL))`. This is the only point I could not understand, and I would really appreciate it if you could explain it to me.

In my naive understanding, I was hoping to find the following expression instead:
```
mix_entropy = -(X_SL * np.log2(X_SL) + X_DL * np.log2(X_DL))
```

**Comment by gpantel** [comment]
Hi Diego,

Yeah, sure. The minus sign is outside of the double parenthesis on line 390
and line 412. If you add some white space it's easier to see:
-(   (X_SL * np.log2(X_SL)) + ( X_DL * np.log2(X_DL))  )
This is equivalent to doing
-(X_SL * np.log2(X_SL)) - ( X_DL * np.log2(X_DL))

Best,
George

**Comment by bondrewd** [comment]
Hi George!

Thank you for your reply! Now I understand it.

In the original expression, there was one pair of parenthesis missing:

-`(` (X_SL * np.log2(X_SL)) + ( X_DL * np.log2(X_DL))  `)`

That made the expression `-A + B` instead of `-A - B`.

Now that you kindly  confirmed to me that the intended expression was:

-(X_SL * np.log2(X_SL)) - ( X_DL * np.log2(X_DL))

I can calculate the mixing entropy.

Thank you very much for your time!

Bests,
Diego

**Comment by gpantel** [comment]
Anytime!
